### ISSUE TITLE
"Last seen"

### ISSUE THREAD

**Issue by Vincents-github** [KeyportApp/Keyport#5]
Also if it's possible to search when our friend was last seen sending a message from their public key.

This gives more value to the user, to be rest assured the message was likely read.

![photo5814668086039653904](https://user-images.githubusercontent.com/39913141/40922078-7f6f03d2-6811-11e8-8466-86ebcd6ffb60.jpg)

**Comment by shravan-shandilya** [comment]
Usually, the other messaging services store this data in some sort of server. Maybe this can be included to be part of the toku protocol. We'll take a look. In the meantime, if you get any ideas about implementing this, let us know here.

**Comment by shravan-shandilya** [comment]
One more interesting suggestion that was floating around in the telegram was to just mark the double tick when the transaction gets confirmed in a block. But, that doesn't mean that the recipient has looked at your message.

**Comment by shravan-shandilya** [comment]
@Vincents-github Last seen has been implemented. Will go into the next release. Thanks for the feature suggestion.
